#!/usr/bin/env bash
# 天枢智投(BestAITrader) 个人自用方案 —— ECS 端 frps 服务端一键安装脚本。
#
# 适用场景：家用宽带无公网 IP，整套业务服务跑在本地 Mac 上，
# 2C2G ECS 仅作为 frp 服务端提供公网入口（frps + 端口转发，不跑业务）。
#
# 用法（在 ECS 上以 root/sudo 执行）：
#   sudo bash scripts/frp_ecs_mac/setup-frp-ecs.sh
#
# 可选环境变量：
#   FRP_VERSION    frp 版本号（默认 0.61.1）
#   FRP_TOKEN      通信令牌（缺省自动生成并持久化到 /etc/frp/frp.token）
#   FRP_BIND_PORT  frps 控制端口（默认 7000）
#   REMOTE_PORT    公网访问端口，即 Mac 上 Web 服务映射到的端口（默认 80）
#
# 安装完成后会打印 FRP_TOKEN 与 REMOTE_PORT，请在 Mac 端 setup-frp-mac.sh 中使用。

set -euo pipefail

FRP_VERSION="${FRP_VERSION:-0.61.1}"
FRP_BIND_PORT="${FRP_BIND_PORT:-7000}"
REMOTE_PORT="${REMOTE_PORT:-80}"
INSTALL_DIR="/opt/frp"
CONF_DIR="/etc/frp"
TOKEN_FILE="$CONF_DIR/frp.token"
UNIT_FILE="/etc/systemd/system/frps.service"

log()  { echo -e "\033[32m[frp-ecs]\033[0m $*"; }
warn() { echo -e "\033[33m[frp-ecs][warn]\033[0m $*"; }
die()  { echo -e "\033[31m[frp-ecs][error]\033[0m $*" >&2; exit 1; }

[[ $(id -u) -eq 0 ]] || die "请用 root 或 sudo 运行本脚本。"
command -v systemctl >/dev/null 2>&1 || die "未找到 systemctl，本脚本仅支持 systemd 的 Linux 发行版。"

# ---------------------------------------------------------------------------
# 1. 确定架构与安装包
# ---------------------------------------------------------------------------
case "$(uname -m)" in
    x86_64|amd64)  ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) die "不支持的 CPU 架构：$(uname -m)" ;;
esac

TARBALL="frp_${FRP_VERSION}_linux_${ARCH}.tar.gz"
URL="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/${TARBALL}"

# ---------------------------------------------------------------------------
# 2. 下载并安装 frps（已安装相同版本则跳过）
# ---------------------------------------------------------------------------
if [[ -x "$INSTALL_DIR/frps" ]] && "$INSTALL_DIR/frps" --version 2>/dev/null | grep -q "$FRP_VERSION"; then
    log "frps $FRP_VERSION 已安装，跳过下载。"
else
    mkdir -p "$INSTALL_DIR"
    if [[ -s "/tmp/$TARBALL" ]]; then
        log "检测到已有安装包 /tmp/$TARBALL，直接复用。"
    else
        log "下载 frp v${FRP_VERSION}（${ARCH}），依次尝试官方与加速镜像..."
        # 每个源限时 120 秒，逐个回退；也可提前手动把 tarball 放到 /tmp/ 复用
        MIRRORS=(
            "$URL"
            "https://ghfast.top/$URL"
            "https://gh-proxy.com/$URL"
        )
        dl_ok=0
        for m in "${MIRRORS[@]}"; do
            log "尝试下载：$m"
            if curl -fsSL --connect-timeout 10 --max-time 120 --retry 2 -o "/tmp/$TARBALL" "$m"; then
                dl_ok=1
                break
            fi
            warn "该源失败，尝试下一个..."
        done
        [[ $dl_ok -eq 1 ]] || die "全部下载源失败。可手动下载 $URL 放到 /tmp/ 后重跑本脚本（会自动复用）。"
    fi
    tar -xzf "/tmp/$TARBALL" -C /tmp
    install -m 0755 "/tmp/frp_${FRP_VERSION}_linux_${ARCH}/frps" "$INSTALL_DIR/frps"
    rm -rf "/tmp/$TARBALL" "/tmp/frp_${FRP_VERSION}_linux_${ARCH}"
    log "frps 已安装到 $INSTALL_DIR/frps（$("$INSTALL_DIR/frps" --version)）"
fi

# ---------------------------------------------------------------------------
# 3. 生成令牌与配置
# ---------------------------------------------------------------------------
mkdir -p "$CONF_DIR"
chmod 700 "$CONF_DIR"

if [[ -n "${FRP_TOKEN:-}" ]]; then
    echo -n "$FRP_TOKEN" > "$TOKEN_FILE"
elif [[ -f "$TOKEN_FILE" ]]; then
    log "复用已有令牌文件 $TOKEN_FILE"
else
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 24 > "$TOKEN_FILE"
    else
        head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$TOKEN_FILE"
    fi
fi
chmod 600 "$TOKEN_FILE"
FRP_TOKEN="$(cat "$TOKEN_FILE")"

log "生成 $CONF_DIR/frps.toml（bindPort=$FRP_BIND_PORT）"
cat > "$CONF_DIR/frps.toml" <<EOF
# Generated by scripts/frp_ecs_mac/setup-frp-ecs.sh
bindPort = $FRP_BIND_PORT
auth.method = "token"
auth.token = "$FRP_TOKEN"
EOF
chmod 600 "$CONF_DIR/frps.toml"

# ---------------------------------------------------------------------------
# 4. 注册 systemd 服务并启动
# ---------------------------------------------------------------------------
log "注册 systemd 服务 frps.service"
cat > "$UNIT_FILE" <<EOF
[Unit]
Description=frps service
After=network.target syslog.target
Wants=network.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/frps -c $CONF_DIR/frps.toml
Restart=on-failure
RestartSec=5s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now frps

# ---------------------------------------------------------------------------
# 5. 结果输出
# ---------------------------------------------------------------------------
sleep 2
if systemctl is-active --quiet frps; then
    log "✓ frps 已启动并设为开机自启。"
else
    warn "frps 启动异常，请执行 journalctl -u frps -f 查看日志。"
fi

PUBLIC_IP=$(curl -fsS -m 5 http://100.100.100.200/latest/meta-data/eipv4 2>/dev/null \
    || curl -fsS -m 5 ifconfig.me 2>/dev/null || echo "<ECS公网IP>")

cat <<EOF

============================================================
 ECS 端 frps 安装完成！
   服务端地址:  $PUBLIC_IP:$FRP_BIND_PORT
   公网入口:    http://$PUBLIC_IP:$REMOTE_PORT  (REMOTE_PORT=$REMOTE_PORT)

 ▶ 重要：请记下以下两项，Mac 端安装时需要：
   FRP_TOKEN:   $FRP_TOKEN
   REMOTE_PORT: $REMOTE_PORT

 后续步骤：
   1. 阿里云控制台安全组放行端口：$FRP_BIND_PORT（仅 Mac 的出口 IP 可见更安全）、$REMOTE_PORT
   2. 在 Mac 上执行 scripts/frp_ecs_mac/setup-frp-mac.sh（见 docs/008 部署文档）
============================================================
EOF
