#!/usr/bin/env bash
# 天枢智投(BestAITrader) 个人自用方案 —— Mac 端 frpc 客户端一键安装脚本。
#
# 适用场景：家用宽带无公网 IP，本机 Docker Desktop 跑整套天枢智投服务
# （入口 http://localhost），通过 frpc 将本机 80 端口穿透到 ECS 公网端口。
#
# 用法（在 Mac 项目根目录执行）：
#   FRP_SERVER_ADDR=<ECS公网IP> FRP_TOKEN=<ECS脚本输出的令牌> bash scripts/setup-frp-mac.sh
#
# 可选环境变量：
#   FRP_VERSION     frp 版本号（默认 0.61.1，需与 ECS 端一致）
#   FRP_SERVER_PORT frps 控制端口（默认 7000）
#   LOCAL_PORT      本机 Web 端口（默认 80，即 docker compose 的 nginx 入口）
#   REMOTE_PORT     ECS 上的公网入口端口（默认 80，需与 ECS 端 REMOTE_PORT 一致）
#
# 脚本动作：安装 frpc → 生成 ~/.frp/frpc.toml → 注册 launchd 开机自启（含防睡眠）。

set -euo pipefail

FRP_VERSION="${FRP_VERSION:-0.61.1}"
FRP_SERVER_ADDR="${FRP_SERVER_ADDR:-}"
FRP_SERVER_PORT="${FRP_SERVER_PORT:-7000}"
FRP_TOKEN="${FRP_TOKEN:-}"
LOCAL_PORT="${LOCAL_PORT:-80}"
REMOTE_PORT="${REMOTE_PORT:-80}"

CONF_DIR="$HOME/.frp"
CONF_FILE="$CONF_DIR/frpc.toml"
LOG_DIR="$CONF_DIR/logs"
PLIST_LABEL="com.bestaitrader.frpc"
PLIST_FILE="$HOME/Library/LaunchAgents/$PLIST_LABEL.plist"

log()  { echo -e "\033[32m[frp-mac]\033[0m $*"; }
warn() { echo -e "\033[33m[frp-mac][warn]\033[0m $*"; }
die()  { echo -e "\033[31m[frp-mac][error]\033[0m $*" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "本脚本仅支持 macOS。"
[[ -n "$FRP_SERVER_ADDR" ]] || die "缺少 FRP_SERVER_ADDR（ECS 公网 IP），用法见脚本头部注释。"
[[ -n "$FRP_TOKEN" ]] || die "缺少 FRP_TOKEN（ECS 端 setup-frp-ecs.sh 输出的令牌）。"

# ---------------------------------------------------------------------------
# 1. 安装 frpc（优先 Homebrew，失败则下载官方二进制）
# ---------------------------------------------------------------------------
FRPC_BIN=""
if command -v frpc >/dev/null 2>&1; then
    FRPC_BIN="$(command -v frpc)"
    log "复用已有 frpc：$FRPC_BIN（$("$FRPC_BIN" --version 2>/dev/null || echo 未知版本)）"
elif command -v brew >/dev/null 2>&1; then
    log "通过 Homebrew 安装 frp..."
    brew install frp
    FRPC_BIN="$(brew --prefix)/bin/frpc"
else
    case "$(uname -m)" in
        x86_64)  ARCH="amd64" ;;
        arm64)   ARCH="arm64" ;;
        *) die "不支持的 CPU 架构：$(uname -m)" ;;
    esac
    TARBALL="frp_${FRP_VERSION}_darwin_${ARCH}.tar.gz"
    URL="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/${TARBALL}"
    log "下载 frp v${FRP_VERSION}（darwin_${ARCH}）..."
    if ! curl -fsSL --retry 3 -o "/tmp/$TARBALL" "$URL"; then
        warn "GitHub 直连失败，尝试镜像加速下载..."
        curl -fsSL --retry 3 -o "/tmp/$TARBALL" "https://ghfast.top/$URL" \
            || die "frp 下载失败，请检查网络，或先安装 Homebrew 后重试。"
    fi
    tar -xzf "/tmp/$TARBALL" -C /tmp
    mkdir -p "$HOME/bin"
    install -m 0755 "/tmp/frp_${FRP_VERSION}_darwin_${ARCH}/frpc" "$HOME/bin/frpc"
    rm -rf "/tmp/$TARBALL" "/tmp/frp_${FRP_VERSION}_darwin_${ARCH}"
    FRPC_BIN="$HOME/bin/frpc"
    log "frpc 已安装到 $FRPC_BIN"
fi

# ---------------------------------------------------------------------------
# 2. 生成 frpc 配置
# ---------------------------------------------------------------------------
mkdir -p "$CONF_DIR" "$LOG_DIR"
chmod 700 "$CONF_DIR"

log "生成 $CONF_FILE"
cat > "$CONF_FILE" <<EOF
# Generated by scripts/setup-frp-mac.sh
serverAddr = "$FRP_SERVER_ADDR"
serverPort = $FRP_SERVER_PORT
auth.method = "token"
auth.token = "$FRP_TOKEN"

[[proxies]]
name = "bestaitrader-web"
type = "tcp"
localIP = "127.0.0.1"
localPort = $LOCAL_PORT
remotePort = $REMOTE_PORT
EOF
chmod 600 "$CONF_FILE"

# ---------------------------------------------------------------------------
# 3. 注册 launchd 用户代理（登录后自启 + 崩溃自动拉起 + 防睡眠）
# ---------------------------------------------------------------------------
# 先卸载旧实例，保证重复执行幂等
launchctl bootout "gui/$(id -u)/$PLIST_LABEL" 2>/dev/null || true
rm -f "$PLIST_FILE"

log "注册 launchd 自启：$PLIST_FILE"
cat > "$PLIST_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$FRPC_BIN</string>
        <string>-c</string>
        <string>$CONF_FILE</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/frpc.out.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/frpc.err.log</string>
</dict>
</plist>
EOF

launchctl bootstrap "gui/$(id -u)" "$PLIST_FILE"

# 防止系统睡眠导致穿透中断（不禁用屏幕关闭）
if ! pmset -g custom | grep -q '^ sleep *0'; then
    warn "当前系统未禁用睡眠，尝试执行 sudo pmset -a sleep 0（失败请手动执行）。"
    sudo -n pmset -a sleep 0 2>/dev/null || warn "自动设置失败，请手动执行：sudo pmset -a sleep 0"
fi

# ---------------------------------------------------------------------------
# 4. 结果校验与输出
# ---------------------------------------------------------------------------
sleep 3
if pgrep -f "frpc -c $CONF_FILE" >/dev/null 2>&1; then
    log "✓ frpc 已启动（登录即自启，崩溃自动重连）。"
else
    warn "frpc 进程未检测到，请查看日志：tail -f $LOG_DIR/frpc.err.log"
fi

if ! curl -fsS -m 3 "http://127.0.0.1:$LOCAL_PORT/" >/dev/null 2>&1; then
    warn "本机 $LOCAL_PORT 端口暂未响应。请先部署业务栈：python3 deploy.py"
fi

ACCESS_PORT_SUFFIX=""
[[ "$REMOTE_PORT" != "80" ]] && ACCESS_PORT_SUFFIX=":$REMOTE_PORT"

cat <<EOF

============================================================
 Mac 端 frpc 安装完成！
   穿透链路:  公网 http://$FRP_SERVER_ADDR$ACCESS_PORT_SUFFIX → ECS:$REMOTE_PORT → 本机:$LOCAL_PORT
   配置文件:  $CONF_FILE
   日志目录:  $LOG_DIR

 后续步骤：
   1. 若尚未部署业务栈：python3 deploy.py（交互式，部署完成后访问 http://localhost）
   2. Docker Desktop 勾选「开机启动」，资源分配内存 10-12GB / CPU 8 线程
   3. 手机/外网浏览器访问 http://$FRP_SERVER_ADDR$ACCESS_PORT_SUFFIX 验证

 常用命令：
   停止穿透:  launchctl bootout gui/$(id -u)/$PLIST_LABEL
   启动穿透:  launchctl bootstrap gui/$(id -u) $PLIST_FILE
   查看日志:  tail -f $LOG_DIR/frpc.err.log
============================================================
EOF
